UPDATE `skillraceclassinfo_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE `ID` = 117 AND `SkillID` = 44 AND `Flags` = 128 AND `MinLevel` = 0 AND `SkillTierID` = 0 AND `SkillCostIndex` = 0;
UPDATE `skillraceclassinfo_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE `ID` = 122 AND `SkillID` = 172 AND `Flags` = 128 AND `MinLevel` = 0 AND `SkillTierID` = 0 AND `SkillCostIndex` = 0;
UPDATE `skillraceclassinfo_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE `ID` = 123 AND `SkillID` = 160 AND `Flags` = 128 AND `MinLevel` = 0 AND `SkillTierID` = 0 AND `SkillCostIndex` = 0;
UPDATE `skillraceclassinfo_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE `ID` = 125 AND `SkillID` = 55 AND `Flags` = 128 AND `MinLevel` = 0 AND `SkillTierID` = 0 AND `SkillCostIndex` = 0;
UPDATE `skillraceclassinfo_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE `ID` = 126 AND `SkillID` = 45 AND `Flags` = 128 AND `MinLevel` = 0 AND `SkillTierID` = 0 AND `SkillCostIndex` = 0;
UPDATE `skillraceclassinfo_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE `ID` = 128 AND `SkillID` = 226 AND `Flags` = 128 AND `MinLevel` = 0 AND `SkillTierID` = 0 AND `SkillCostIndex` = 0;
UPDATE `skillraceclassinfo_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE `ID` = 129 AND `SkillID` = 173 AND `Flags` = 128 AND `MinLevel` = 0 AND `SkillTierID` = 0 AND `SkillCostIndex` = 0;
UPDATE `skillraceclassinfo_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE `ID` = 131 AND `SkillID` = 118 AND `Flags` = 146 AND `MinLevel` = 1 AND `SkillTierID` = 0 AND `SkillCostIndex` = 0;
UPDATE `skillraceclassinfo_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE `ID` = 133 AND `SkillID` = 46 AND `Flags` = 128 AND `MinLevel` = 0 AND `SkillTierID` = 0 AND `SkillCostIndex` = 0;
UPDATE `skillraceclassinfo_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE `ID` = 135 AND `SkillID` = 54 AND `Flags` = 128 AND `MinLevel` = 0 AND `SkillTierID` = 0 AND `SkillCostIndex` = 0;
UPDATE `skillraceclassinfo_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE `ID` = 136 AND `SkillID` = 229 AND `Flags` = 128 AND `MinLevel` = 20 AND `SkillTierID` = 0 AND `SkillCostIndex` = 0;
UPDATE `skillraceclassinfo_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE `ID` = 138 AND `SkillID` = 136 AND `Flags` = 128 AND `MinLevel` = 0 AND `SkillTierID` = 0 AND `SkillCostIndex` = 0;
UPDATE `skillraceclassinfo_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE `ID` = 140 AND `SkillID` = 43 AND `Flags` = 128 AND `MinLevel` = 0 AND `SkillTierID` = 0 AND `SkillCostIndex` = 0;
UPDATE `skillraceclassinfo_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE `ID` = 142 AND `SkillID` = 176 AND `Flags` = 128 AND `MinLevel` = 0 AND `SkillTierID` = 0 AND `SkillCostIndex` = 0;
UPDATE `skillraceclassinfo_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE `ID` = 144 AND `SkillID` = 228 AND `Flags` = 128 AND `MinLevel` = 0 AND `SkillTierID` = 0 AND `SkillCostIndex` = 0;
UPDATE `skillraceclassinfo_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE `ID` = 145 AND `SkillID` = 413 AND `Flags` = 128 AND `MinLevel` = 40 AND `SkillTierID` = 0 AND `SkillCostIndex` = 0;
UPDATE `skillraceclassinfo_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE `ID` = 147 AND `SkillID` = 414 AND `Flags` = 128 AND `MinLevel` = 0 AND `SkillTierID` = 0 AND `SkillCostIndex` = 0;
UPDATE `skillraceclassinfo_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE `ID` = 148 AND `SkillID` = 415 AND `Flags` = 128 AND `MinLevel` = 0 AND `SkillTierID` = 0 AND `SkillCostIndex` = 0;
UPDATE `skillraceclassinfo_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE `ID` = 21 AND `SkillID` = 293 AND `Flags` = 128 AND `MinLevel` = 40 AND `SkillTierID` = 0 AND `SkillCostIndex` = 0;
UPDATE `skillraceclassinfo_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE `ID` = 246 AND `SkillID` = 433 AND `Flags` = 128 AND `MinLevel` = 0 AND `SkillTierID` = 0 AND `SkillCostIndex` = 0;
UPDATE `skillraceclassinfo_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE `ID` = 4 AND `SkillID` = 95 AND `Flags` = 640 AND `MinLevel` = 0 AND `SkillTierID` = 0 AND `SkillCostIndex` = 0;
UPDATE `skillraceclassinfo_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE `ID` = 40 AND `SkillID` = 98 AND `Flags` = 128 AND `MinLevel` = 0 AND `SkillTierID` = 0 AND `SkillCostIndex` = 0;
UPDATE `skillraceclassinfo_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE `ID` = 48 AND `SkillID` = 109 AND `Flags` = 128 AND `MinLevel` = 0 AND `SkillTierID` = 0 AND `SkillCostIndex` = 0;
UPDATE `skillraceclassinfo_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE `ID` = 6 AND `SkillID` = 162 AND `Flags` = 128 AND `MinLevel` = 0 AND `SkillTierID` = 0 AND `SkillCostIndex` = 0;

UPDATE `playercreateinfo_skills` SET `raceMask` = 0, `classMask` = 0 WHERE skill = 109 AND `rank` = 0 AND `comment` = "Language: Orcish";
UPDATE `playercreateinfo_skills` SET `raceMask` = 0, `classMask` = 0 WHERE skill = 118 AND `rank` = 0 AND `comment` = "Dual Wield";
UPDATE `playercreateinfo_skills` SET `raceMask` = 0, `classMask` = 0 WHERE skill = 136 AND `rank` = 0 AND `comment` = "Staves";
UPDATE `playercreateinfo_skills` SET `raceMask` = 0, `classMask` = 0 WHERE skill = 160 AND `rank` = 0 AND `comment` = "Two-Handed Maces";
UPDATE `playercreateinfo_skills` SET `raceMask` = 0, `classMask` = 0 WHERE skill = 162 AND `rank` = 0 AND `comment` = "Unarmed";
UPDATE `playercreateinfo_skills` SET `raceMask` = 0, `classMask` = 0 WHERE skill = 172 AND `rank` = 0 AND `comment` = "Two-Handed Axes";
UPDATE `playercreateinfo_skills` SET `raceMask` = 0, `classMask` = 0 WHERE skill = 173 AND `rank` = 0 AND `comment` = "Daggers";
UPDATE `playercreateinfo_skills` SET `raceMask` = 0, `classMask` = 0 WHERE skill = 176 AND `rank` = 0 AND `comment` = "Thrown";
UPDATE `playercreateinfo_skills` SET `raceMask` = 0, `classMask` = 0 WHERE skill = 226 AND `rank` = 0 AND `comment` = "Crossbows";
UPDATE `playercreateinfo_skills` SET `raceMask` = 0, `classMask` = 0 WHERE skill = 228 AND `rank` = 0 AND `comment` = "Wands";
UPDATE `playercreateinfo_skills` SET `raceMask` = 0, `classMask` = 0 WHERE skill = 229 AND `rank` = 0 AND `comment` = "Polearms";
UPDATE `playercreateinfo_skills` SET `raceMask` = 0, `classMask` = 0 WHERE skill = 293 AND `rank` = 0 AND `comment` = "Plate";
UPDATE `playercreateinfo_skills` SET `raceMask` = 0, `classMask` = 0 WHERE skill = 413 AND `rank` = 0 AND `comment` = "Mail";
UPDATE `playercreateinfo_skills` SET `raceMask` = 0, `classMask` = 0 WHERE skill = 414 AND `rank` = 0 AND `comment` = "Leather";
UPDATE `playercreateinfo_skills` SET `raceMask` = 0, `classMask` = 0 WHERE skill = 415 AND `rank` = 0 AND `comment` = "Cloth";
UPDATE `playercreateinfo_skills` SET `raceMask` = 0, `classMask` = 0 WHERE skill = 43 AND `rank` = 0 AND `comment` = "Swords";
UPDATE `playercreateinfo_skills` SET `raceMask` = 0, `classMask` = 0 WHERE skill = 433 AND `rank` = 0 AND `comment` = "Shield";
UPDATE `playercreateinfo_skills` SET `raceMask` = 0, `classMask` = 0 WHERE skill = 44 AND `rank` = 0 AND `comment` = "Axes";
UPDATE `playercreateinfo_skills` SET `raceMask` = 0, `classMask` = 0 WHERE skill = 45 AND `rank` = 0 AND `comment` = "Bows";
UPDATE `playercreateinfo_skills` SET `raceMask` = 0, `classMask` = 0 WHERE skill = 46 AND `rank` = 0 AND `comment` = "Guns";
UPDATE `playercreateinfo_skills` SET `raceMask` = 0, `classMask` = 0 WHERE skill = 54 AND `rank` = 0 AND `comment` = "Maces";
UPDATE `playercreateinfo_skills` SET `raceMask` = 0, `classMask` = 0 WHERE skill = 55 AND `rank` = 0 AND `comment` = "Two-Handed Swords";
UPDATE `playercreateinfo_skills` SET `raceMask` = 0, `classMask` = 0 WHERE skill = 95 AND `rank` = 0 AND `comment` = "Defense";
UPDATE `playercreateinfo_skills` SET `raceMask` = 0, `classMask` = 0 WHERE skill = 98 AND `rank` = 0 AND `comment` = "Language: Common";

UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 107 AND Note = "Block";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 1180 AND Note = "Daggers";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 15590 AND Note = "Fist Weapons";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 196 AND Note = "One-Handed Axes";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 197 AND Note = "Two-Handed Axes";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 198 AND Note = "One-Handed Maces";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 199 AND Note = "Two-Handed Maces";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 200 AND Note = "Polearm";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 201 AND Note = "One-Handed Swords";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 202 AND Note = "Two-Handed Swords";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 203 AND Note = "Unarmed";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 204 AND Note = "Defense";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 227 AND Note = "Staves";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 2567 AND Note = "Thrown";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 264 AND Note = "Bows";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 266 AND Note = "Guns";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 2764 AND Note = "Throw";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 27762 AND Note = "Libram";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 27763 AND Note = "Totem";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 27764 AND Note = "Idol";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 3127 AND Note = "Parry";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 5009 AND Note = "Wands";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 5011 AND Note = "Crossbows";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 5019 AND Note = "Shoot";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 52665 AND Note = "Sigil";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 674 AND Note = "Dual Wield";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 75 AND Note = "Auto Shot";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 750 AND Note = "Plate";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 81 AND Note = "Dodge";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 8737 AND Note = "Mail";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 9077 AND Note = "Leather";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 9078 AND Note = "Cloth";
UPDATE `playercreateinfo_spell_custom` SET `racemask` = 0, `classmask` = 0 WHERE Spell = 9116 AND Note = "Shield";

UPDATE `skilllineability_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE ID = 252 AND SkillLine = 43 AND Spell = 43;
UPDATE `skilllineability_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE ID = 248 AND SkillLine = 44 AND Spell = 44;
UPDATE `skilllineability_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE ID = 246 AND SkillLine = 45 AND Spell = 45;
UPDATE `skilllineability_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE ID = 251 AND SkillLine = 46 AND Spell = 46;
UPDATE `skilllineability_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE ID = 254 AND SkillLine = 54 AND Spell = 54;
UPDATE `skilllineability_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE ID = 256 AND SkillLine = 55 AND Spell = 55;
UPDATE `skilllineability_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE ID = 490 AND SkillLine = 95 AND Spell = 95;
UPDATE `skilllineability_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE ID = 610 AND SkillLine = 118 AND Spell = 118;
UPDATE `skilllineability_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE ID = 700 AND SkillLine = 136 AND Spell = 136;
UPDATE `skilllineability_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE ID = 3214 AND SkillLine = 160 AND Spell = 160;
UPDATE `skilllineability_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE ID = 1236 AND SkillLine = 162 AND Spell = 162;
UPDATE `skilllineability_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE ID = 3213 AND SkillLine = 172 AND Spell = 172;
UPDATE `skilllineability_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE ID = 1387 AND SkillLine = 173 AND Spell = 173;
UPDATE `skilllineability_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE ID = 1550 AND SkillLine = 176 AND Spell = 176;
UPDATE `skilllineability_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE ID = 2929 AND SkillLine = 226 AND Spell = 226;
UPDATE `skilllineability_dbc` SET `RaceMask` = 0, `ClassMask` = 0 WHERE ID = 2927 AND SkillLine = 228 AND Spell = 228;
